[project]
name = "scrcpy-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "adbutils>=2.12.0",
    "mcp>=1.22.0",
]
